services:
  postgres:
    image: postgres:16
    container_name: postgres_dwh
    restart: always
    environment:
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_password
      POSTGRES_DB: dwh_db
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
      - ./datasets:/datasets

volumes:
  postgres_data: